version: "3.8"
services:
  db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  app:
    container_name: node-app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      PGUSER: ${POSTGRES_USER}
      PGHOST: db
      PGDATABASE: ${POSTGRES_DB}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: 5432
    volumes:
      - ./order-images:/usr/src/app/orderImages
volumes:
  order-images:
  pgdata:
